//
//  ListHeroPresenter.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 23/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListHeroPresentationLogic {
    func presentAllRoles(roles: [String])
    func presentHeroBasedOnRoles(hero: [Hero])
}

class ListHeroPresenter: ListHeroPresentationLogic {
    weak var viewController: ListHeroDisplayLogic?
    
    func presentAllRoles(roles: [String]) {
        viewController?.displayRoles(roles: roles)
    }
    
    func presentHeroBasedOnRoles(hero: [Hero]) {
        viewController?.displayHeroesBasedOnRoles(heroes: hero)
    }
}
