//
//  ListHeroInteractor.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 23/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Realm
import RealmSwift

protocol ListHeroBusinessLogic {
    func getAllRoles()
    func getHeroBasedOnRoles(key: String)
}

class ListHeroInteractor: ListHeroBusinessLogic {
    var presenter: ListHeroPresentationLogic?
    
    func getAllRoles() {
        let allRoles = HeroHelper.instance.getAllRoles()
        presenter?.presentAllRoles(roles: allRoles)
    }
    
    func getHeroBasedOnRoles(key: String) {
        let filteredHero = HeroHelper.instance.getHeroByRoles(role: key)
        presenter?.presentHeroBasedOnRoles(hero: filteredHero)
    }
}
