//
//  ListHeroInteractorTests.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dota
import XCTest

class ListHeroInteractorTests: XCTestCase {
    class ListHeroPresenterMock: ListHeroPresentationLogic {
        var presentAllRolesCalled = false
        var presentHeroBasedOnRolesCalled = false
        
        func presentAllRoles(roles: [String]) {
            presentAllRolesCalled = true
        }
        
        func presentHeroBasedOnRoles(hero: [Hero]) {
            presentHeroBasedOnRolesCalled = true
        }
    }
    
    var interactor: ListHeroInteractor!
    var presenter: ListHeroPresenterMock!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        interactor = ListHeroInteractor()
        presenter = ListHeroPresenterMock()
        
        interactor.presenter = presenter
    }
    
    override func tearDown() {
        interactor = nil
        presenter = nil
        super.tearDown()
    }
    
    func testGetAllRoles() {
        //When
        interactor.getAllRoles()
        
        //Then
        XCTAssertTrue(presenter.presentAllRolesCalled, "presentAllRoles should be called")
    }
    
    func testGetHeroBasedOnRoles() {
        //When
        interactor.getHeroBasedOnRoles(key: "")
        
        //Then
        XCTAssertTrue(presenter.presentHeroBasedOnRolesCalled, "presentHeroBasedOnRoles should be called")
    }
}
