//
//  ListHeroPresenterTests.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dota
import XCTest

class ListHeroPresenterTests: XCTestCase {
    class ListHeroViewControllerMock: ListHeroDisplayLogic {
        var displayRolesCalled = false
        var displayHeroesBasedOnRolesCalled = false
        
        func displayRoles(roles: [String]) {
            displayRolesCalled = true
        }
        
        func displayHeroesBasedOnRoles(heroes: [Hero]) {
            displayHeroesBasedOnRolesCalled = true
        }
    }
    
    var presenter: ListHeroPresenter!
    var viewController: ListHeroViewControllerMock!
    
    override func setUp() {
        super.setUp()
        presenter = ListHeroPresenter()
        viewController = ListHeroViewControllerMock()
        
        presenter.viewController = viewController
    }
    
    override func tearDown() {
        presenter = nil
        viewController = nil
        super.tearDown()
    }
    
    func testPresentAllRoles() {
        //When
        presenter.presentAllRoles(roles: [""])
        
        //Then
        XCTAssertTrue(viewController.displayRolesCalled, "displayRoles should be called")
    }
    
    func testPresentHeroBasedOnRoles() {
        //When
        presenter.presentHeroBasedOnRoles(hero: [])
        
        //Then
        XCTAssertTrue(viewController.displayHeroesBasedOnRolesCalled, "displayHeroesBasedOnRoles should be called")
    }
}
