//
//  HeroDetailRouter.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 23/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HeroDetailRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

class HeroDetailRouter: NSObject, HeroDetailRoutingLogic {
  weak var viewController: HeroDetailViewController?
  
}
