//
//  SplashScreenViewControllerTests.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dota
import XCTest

class SplashScreenViewControllerTests: XCTestCase {
    class SplashScreenInteractorMock: SplashScreenBusinessLogic {
        var getHeroDataCalled = false
        
        func getHeroData() {
            getHeroDataCalled = true
        }
    }
    
    var vc: SplashScreenViewController!
    var interactor: SplashScreenInteractorMock!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupSplashScreenViewController()
        interactor = SplashScreenInteractorMock()
        
        vc.interactor = interactor
    }
    
    override func tearDown() {
        window = nil
        vc = nil
        interactor = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupSplashScreenViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "SplashScreen", bundle: bundle)
        vc = storyboard.instantiateViewController(withIdentifier: "SplashScreen") as? SplashScreenViewController
    }
    
    func loadView() {
        window.addSubview(vc.view)
    }
    
    func testShouldGetHeroData() {
        // When
        loadView()
        
        // Then
        XCTAssertTrue(interactor.getHeroDataCalled, "getHeroDataShouldBeCalled")
    }
}
