//
//  SplashScreenInteractorTests.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dota
import XCTest

class SplashScreenInteractorTests: XCTestCase {
    class SplashScreenPresenterMock: SplashScreenPresentationLogic {
        var presentSuccessLoadingDataCalled = false
        var presentErrorLoadDataCalled = false
        
        func presentSuccessLoadingData() {
            presentSuccessLoadingDataCalled = true
        }
        
        func presentErrorLoadData() {
            presentErrorLoadDataCalled = true
        }
    }
    
    var interactor: SplashScreenInteractor!
    var presenter: SplashScreenPresenterMock!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        interactor = SplashScreenInteractor()
        presenter = SplashScreenPresenterMock()
        interactor.presenter = presenter
    }
    
    override func tearDown() {
        interactor = nil
        presenter = nil
        super.tearDown()
    }
    
    func testSuccessLoadData() {
        // When
        interactor.getHeroData()
        
        // Then
        Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true, block: { timer in
            XCTAssertTrue(self.presenter.presentSuccessLoadingDataCalled, "success loading data should be called")
        })
    }
}
