//
//  HeroDetailViewControllerTests.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dota
import XCTest

class HeroDetailViewControllerTests: XCTestCase {
    class HeroDetailInteractorMock: HeroDetailBusinessLogic {
        var getSimilarHeroCalled = false
        
        func getSimilarHero(primaryAttribute: String) {
            getSimilarHeroCalled = true
        }
    }
    
    var viewController: HeroDetailViewController!
    var interactor: HeroDetailInteractorMock!
    var window: UIWindow!
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        interactor = HeroDetailInteractorMock()
        setupHeroDetailViewController()
        
        viewController.interactor = interactor
    }
    
    override func tearDown() {
        window = nil
        viewController = nil
        interactor = nil
        super.tearDown()
    }
    
    func setupHeroDetailViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "HeroDetail", bundle: bundle)
        viewController = storyboard.instantiateViewController(withIdentifier: "HeroDetail") as? HeroDetailViewController
    }
    
    func loadView() {
        window.addSubview(viewController.view)
    }
    
    func testViewDidLoad() {
        //When
        loadView()
        
        //Then
        XCTAssertTrue(interactor.getSimilarHeroCalled, "getSimilarHero should be called")
    }
    
}
