//
//  HeroDetailInteractorTests.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dota
import XCTest

class HeroDetailInteractorTests: XCTestCase {
    class HeroDetailPresenterMock: HeroDetailPresentationLogic {
        var presentSimilarHeroCalled = false
        
        func presentSimilarHero(hero: [Hero]) {
            presentSimilarHeroCalled = true
        }
    }
    
    var interactor: HeroDetailInteractor!
    var presenter: HeroDetailPresenterMock!
    
    override func setUp() {
        super.setUp()
        presenter = HeroDetailPresenterMock()
        interactor = HeroDetailInteractor()
        
        interactor.presenter = presenter
    }
    
    override func tearDown() {
        presenter = nil
        interactor = nil
        super.tearDown()
    }
    
    func testDoSomething() {
        //When
        interactor.getSimilarHero(primaryAttribute: "")
        
        //Then
        XCTAssertTrue(presenter.presentSimilarHeroCalled, "presentSimilarHero should be called")
    }
}
