//
//  HeroDetailPresenterTests.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 27/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dota
import XCTest

class HeroDetailPresenterTests: XCTestCase {
    class HeroDetailViewControllerMock: HeroDetailDisplayLogic {
        var displaySimilarHeroCalled = false
        
        func displaySimilarHero(hero: [Hero]) {
            displaySimilarHeroCalled = true
        }
    }
    
    var presenter: HeroDetailPresenter!
    var viewController: HeroDetailViewControllerMock!
    
    override func setUp() {
        super.setUp()
        presenter = HeroDetailPresenter()
        viewController = HeroDetailViewControllerMock()
        
        presenter.viewController = viewController
    }
    
    override func tearDown() {
        presenter = nil
        viewController = nil
        super.tearDown()
    }
    
    func testDisplaySimilarHero() {
        //When
        presenter.presentSimilarHero(hero: [])
        
        //Then
        XCTAssertTrue(viewController.displaySimilarHeroCalled, "displaySimilarHero should be called")
    }
    
}
