//
//  SplashScreenRouter.swift
//  dota
//
//  Created by Muhammad Ilham Ramadhan on 23/07/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SplashScreenRoutingLogic {
    func routeToHeroListViewController(viewController: UIViewController)
}


class SplashScreenRouter: NSObject, SplashScreenRoutingLogic {
    weak var viewController: SplashScreenViewController?
    
    func routeToHeroListViewController(viewController: UIViewController) {
        let mainStoryboard: UIStoryboard = UIStoryboard(name: DotaAppsConstants.Storyboard.listHero, bundle: nil)
        let listHeroViewController: ListHeroViewController  = mainStoryboard.instantiateViewController(withIdentifier: DotaAppsConstants.Storyboard.listHero) as! ListHeroViewController
        
        let nav = UINavigationController(rootViewController: listHeroViewController)
        
        UIApplication.shared.windows.first?.rootViewController = nav
        UIApplication.shared.windows.first?.makeKeyAndVisible()
    }
}
